-keep class androidx.startup.AppInitializer
-keep class * extends androidx.startup.Initializer
-keep class androidx.multidex.** { *; }
-keep class androidx.core.app.CoreComponentFactory
-keep class com.pt.** { *; }
-keep class kotlin.** { *; }
-keep class kotlinx.coroutines.** { *; }
