package com.pt.common.stable

const val DB_PREF: String = "sharedPrefApp.db"
const val PREF_TABLE_NAME: String = "prefTable"
const val KEY_PRI: String = "priPref"
const val KEY_PREF: String = "keyPref"
const val STRING_PREF: String = "stringPref"
const val INT_PREF: String = "intPref"
const val BOOL_PREF: String = "booleanPref"
const val LONG_PREF: String = "longPref"

const val DATA_AD_NAME: String = "appForAds.db"
const val AD_TABLE_NAME: String = "adTable"
const val ID_AD_DATA: String = "idAdData"
const val ID_FIRST_DATA: String = "firstDataAd"
const val FIRST_DATA: String = "iAmIn"
const val ID_Showed_TIME: String = "idShowedTime"
const val ID_NEXT_IS_INTERSTITIAL: String = "isLastIsInterstitial"


const val DATA_CALL: String = "appForCalls.db"
const val CALL_TABLE_NAME: String = "callTable"
const val ID_CALL_PRI: String = "idCallPri"
const val ID_NAME: String = "nameID"
const val ID_COLOR: String = "colorID"


const val DB_FILE_NAME: String = "favorite_file.dp"
const val ID_FILE: String = "idFile"
const val FILE_NAME: String = "nameFile"
const val PATH_FILE: String = "filePath"
const val PATH_VIR_NAME: String = "filePathVir"
const val URI_FILE: String = "uriFile"
const val SIZE_FILE: String = "sizeFile"
const val FILE_TYPE_FILE: String = "typeFile"
const val SUB_NUMBER_FILE: String = "subNumberFiles"
const val DATA_MOD_FILE: String = "dataModified"
const val VIR_NAME_FILE: String = "forVirFile"
const val TABLE_FILE: String = "favoritesFile"
const val ID_TWO_FILE: String = "idTwoFile"
const val VIRTUAL_NAME_FILE: String = "virName"
const val VIR_NUMBER_FILE: String = "fileNumVir"
const val TABLE_TWO_FILE: String = "virtualTable"

const val DATABASE_PLAYLIST: String = "music_playlist.dp"
const val ID_MUSIC: String = "id"
const val MUSIC_TIT: String = "musicTitle"
const val SONG_ARTIST: String = "musicArtist"
const val PATH_SONG: String = "musicPath"
const val BELONG_PLAYLIST: String = "whichPlaylist"
const val IS_DEFAULT_PLAYLIST: String = "isDefaultPlaylist"
const val LIST_PATH: String = "playlistPath"
const val TABLE_MUSIC: String = "musicTable"

const val ID_PLAYLIST: String = "idPlay"
const val PLAYLIST_NAME: String = "playlistTitle"
const val PLAYLIST_FIRST: String = "playlistFirstSong"
const val PLAYLIST_POSITION: String = "playlistLastPotion"
const val PLAYLIST_NUMBERS: String = "playlistSongsNumber"
const val PLAYLIST_TABLE: String = "playlistTable"

const val DATABASE_GAL: String = "favoriteImage.dp"
const val ID_GAL: String = "id"
const val MEDIA_NAME: String = "nameMedia"
const val PATH_GAL: String = "mediaPath"
const val PATH_GAL_HID: String = "mediaPathIsHid"
const val URI_GAL: String = "uriMedia"
const val IS_IMAGE_GAL: String = "imageVideo"
const val SIZE_GAL: String = "sizeMedia"
const val WIDTH_GAL: String = "widthMedia"
const val HEIGHT_GAL: String = "mediaHeight"
const val DATA_MODIFIED_GAL: String = "dataModified"
const val IS_HIDDEN_GALLERY: String = "isHiddenGallery"
const val TABLE_GAL: String = "popularMedia"
const val ID_SEEK_GAL: String = "idSeek"
const val VIDEOS_NAME_GAL: String = "videoName"
const val VIDEOS_TIME_GAL: String = "videoTime"
const val TABLE_SEEK_GAL: String = "videosMedia"